# Header
menu:
  Home: /
  Archives: /archives
  About: /about
  # Tags: /tags
  # Categories: /categories
  bilibili: https://space.bilibili.com/85520747
# rss: /atom.xml
github: https://github.com/CassiniHuy
# banner: "images/banner.jpg"

# Content
excerpt_link: Read More
fancybox: true
recent_posts_limits: 5

# Sidebar
sidebar: right
widgets:
- about_me
- category
# - tag
- tagcloud
- archive
# - calendar
- recent_posts
- links

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
google_analytics:
baidu_tongji:
favicon: /images/favicon.ico

twitter:
fb_admins:
fb_app_id:

# Toc
toc:
  article: true   ## show contents in article.
  aside: true     ## show contents in aside.
# Scroll to top
go_top: true

# baidu share
baidushare: true

# blogroll
links:
- name: Zhiyu's Blog 
  link: https://qgrain.github.io/
- name: 中文马克思主义文库
  link: https://www.marxists.org/chinese/marx/index.htm
- name: 汉典
  link: https://www.zdic.net/

# about me
about_me:
  title: ABOUT ME
  gravatar: cassiniwei@outlook.com
  avatar: /images/coffee_onetwo.jpg
  texts:
  - Confusion.

# display updated
display_updated: false

# 不蒜子
busuanzi: false

# calendar
calendar:
  language: zh-CN

# hexo-renderer-pandoc (or hexo-renderer-kramed) required for full MathJax support.
mathjax:
  enable: true
  # See: https://mhchem.github.io/MathJax-mhchem/
  mhchem: true

# valine comment system. https://valine.js.org
valine:
  enable: true
  appId: t2m58rhzOMoJTD21pEaJ5gHJ-MdYXbMMI
  appKey: FCXmx3W5LaZfCPys3TBd1uul
  # appId: sA5b5bSKVOumVxcKtX8NUqFk-gzGzoHsz
  # appKey: glFUguQG84y2GTeKhQR0RNAX
  notify: true # Mail notifier
  verify: true # Verification code
  placeholder: Comment notification enabled! Fill in your E-Mail address so you can get notified when there is a reply. # Comment box placeholder
  avatar: mm # Gravatar style
  guest_info: nick,mail,link # Custom comment header
  pageSize: 10 # Pagination size
  language: # Language, available values: en, zh-cn
  visitor: true # Article reading statistic
  comment_count: true # If false, comment count will only be displayed in post page, not in home page
  recordIP: true # Whether to record the commenter IP
  serverURLs: https://t2m58rhz.api.lncldglobal.com # When the custom domain name is enabled, fill it in here (it will be detected automatically by default, no need to fill in)
  #post_meta_order: 0
